[FIX] AttributeError: 'str' object has no attribute '_execute_on_connection'. Passing a string to connection.execute() was removed in version 2.0 of sqlalchemy https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Connection.execute